Home page fixed
cannoli-deco/cannoli-app pull request #15
Opened 2020-09-17 14:08 UTC by xhhh-mendes

please review

2020-09-17 14:24 UTC, IvanImp requested changes
Good work, but there are some issues that you can look into
1. The picture you showed in messenger, the "Gas" label overlapped with "Transport" with no color on it
2. The "Set Emission Goal" can look more like a button rather than label
3. Set Emission Goal popup can gives more hint like "Emission Goal (kg) ____________"
4. Color of the "Save" can try emphasisColor
5. However I'm not sure about the donut-shaped graph, maybe someone can give more insight on it.

Thanks for your work anyway :) Screenshot can leave it here in PR instead of messenger when update

2020-09-17 17:25 UTC, pu-pu commented on pubspec.yaml
> +    - family: Raleway
Are you using this font? Couldn't find any reference.

2020-09-17 17:29 UTC, pu-pu requested changes
Mostly the same issues as Ivan mentioned. One additional point regarding the alarm clock icon on the second screenshot. I don't understand that symbol. Is it the set emission goals button?

2020-09-17 22:21 UTC, RW21 requested changes
Thanks for the PR. 😄 
I think the donut shape graph is fine.
I get errors when there are no entries in some emission category.
```
The method '[]' was called on null.
```

2020-09-18 02:56 UTC, xhhh-mendes commented
![1234](https://user-images.githubusercontent.com/48171908/93550001-dc5d9380-f9ad-11ea-87db-802776fc5bb4.PNG)

1. As Gregoria said, self-adding emission goal is disabled for now.

2. There is no 'Gas' section in the pie chart because gas input hasn't been done.

3. The error @RW21 mentioned, the error occurs even there are entries. I couldn't figure it out, but it seems doesn't affect functionality.

2020-09-18 03:14 UTC, RW21 requested changes
Thanks for the fixes 😄 
- Also, can you add text if there is no emission for the day? 

Actually, it works.
~~Can you also try to fix getting the home energy data in the pie chart? (I think something with source_id is broken because my `source_id` for `Home Energy` was 43. )~~
~~or do you think we should do this in another task?~~

2020-09-18 03:14 UTC, RW21 commented on lib/scenes/home_page.dart
> +  String _emissionGoal = '1000 KG/CO\u2082';
Please get sum of today's emission.

2020-09-18 03:15 UTC, IvanImp approved these changes
Is there a need to split up home energy into micro parts (gas, electricity, water). Maybe someone else could give their thoughts on this as well. In the mean time, we could merge this first and the splitting can be another feature. Else, LGMT. Thanks for the work

2020-09-18 03:31 UTC, pu-pu approved these changes

2020-09-18 10:00 UTC, xhhh-mendes commented
@RW21
Rather than directly display text, I still use a pie chart which looks like this.
![no](https://user-images.githubusercontent.com/48171908/93585044-8c042700-f9e9-11ea-8785-e8856197b445.PNG)
Does it look good to you?

2020-09-18 10:04 UTC, xhhh-mendes commented
@RW21 I forgot to push lol, I'll push it first

2020-09-19 06:30 UTC, RW21 approved these changes
Thanks 😄

2020-09-19 06:33 UTC, merged